FROM openjdk:8-jdk-alpine

LABEL org.label-schema.vendor="Q-rapids Forecast REST" \
      maintainer="Mikolaj Komisarek <mikolajkomisarek@outlook.com>"

ADD jar/qrapids-dashboard-0.3.5.jar app.jar
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]